variable customer-name {}
variable location {}
variable location-prefix {}
variable env-prefix {}
variable environment {}
variable createdby {}
variable creationdate {}
variable spoke-vnet-address-space {}
variable aks-default-subnet-address-space {}
variable aks-acquisition-subnet-address-space {}
variable aks-imageprocessing-subnet-address-space {}
variable pe-subnet-address-space {}
variable appsvc-subnet-address-space {}
variable aks-system-node-vm-size {}
variable firewall-private-ip {}
variable la-workspace-resource-id {}
variable aks-system-nodepool-vm-size {}